/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    LogoutButton: typeof import('./src/components/LogoutButton.vue')['default']
    SystemMessage: typeof import('./src/components/SystemMessage.vue')['default']
  }
}
